# rag/config.py

# Chroma DB 저장 위치
CHROMA_DIR = "./rag/chroma_db"

# DSM-5-TR PDF 파일 위치 (프로젝트 루트에 있다고 가정)
DSM_PDF_PATH = "./documents/DSM-5-TR.pdf"

# 컬렉션 이름
DSM_COLLECTION_NAME = "dsm5tr"


# treatment
TREATMENT_DOCS_DIR = "./documents"
TREATMENT_PDF_FILES = [
    "ocd.pdf",
    "depression.pdf",
    "anxietyandpanic.pdf",
    "bipolar.pdf",
    "ptsd.pdf",
    "adhd.pdf",
]
TREATMENT_COLLECTION_NAME = "treatment"

KNOWN_DISORDERS = [

  "Intellectual Developmental Disorder (Intellectual Disability)",
  "Global Developmental Delay",
  "Unspecified Intellectual Developmental Disorder (Intellectual Disability)",
  "Language Disorder",
  "Speech Sound Disorder",
  "Childhood-Onset Fluency Disorder (Stuttering)",
  "Social (Pragmatic) Communication Disorder",
  "Unspecified Communication Disorder",
  "Autism Spectrum Disorder",
  "Attention-Deficit/Hyperactivity Disorder",
  "Other Specified Attention-Deficit/Hyperactivity Disorder",
  "Unspecified Attention-Deficit/Hyperactivity Disorder",
  "Specific Learning Disorder",
  "Developmental Coordination Disorder",
  "Stereotypic Movement Disorder",
  "Tourette's Disorder",
  "Tic Disorders",
  "Persistent (Chronic) Motor or Vocal Tic Disorder",
  "Provisional Tic Disorder",
  "Other Specified Tic Disorder",
  "Unspecified Tic Disorder",
  "Other Specified Neurodevelopmental Disorder",
  "Unspecified Neurodevelopmental Disorder",

  "Schizotypal (Personality) Disorder",
  "Delusional Disorder",
  "Brief Psychotic Disorder",
  "Schizophreniform Disorder",
  "Schizophrenia",
  "Schizoaffective Disorder",
  "Substance/Medication-Induced Psychotic Disorder",
  "Psychotic Disorder Due to Another Medical Condition",
  "Catatonia Associated With Another Mental Disorder",
  "Catatonic Disorder Due to Another Medical Condition",
  "Unspecified Catatonia",
  "Other Specified Schizophrenia Spectrum and Other Psychotic Disorder",
  "Unspecified Schizophrenia Spectrum and Other Psychotic Disorder",

  "Bipolar I Disorder",
  "Bipolar II Disorder",
  "Cyclothymic Disorder",
  "Substance/Medication-Induced Bipolar and Related Disorder",
  "Bipolar and Related Disorder Due to Another Medical Condition",
  "Other Specified Bipolar and Related Disorder",
  "Unspecified Bipolar and Related Disorder",
  "Unspecified Mood Disorder",

  "Disruptive Mood Dysregulation Disorder",
  "Major Depressive Disorder",
  "Persistent Depressive Disorder",
  "Premenstrual Dysphoric Disorder",
  "Substance/Medication-Induced Depressive Disorder",
  "Depressive Disorder Due to Another Medical Condition",
  "Other Specified Depressive Disorder",
  "Unspecified Depressive Disorder",

  "Separation Anxiety Disorder",
  "Selective Mutism",
  "Specific Phobia",
  "Social Anxiety Disorder",
  "Panic Disorder",
  "Agoraphobia",
  "Generalized Anxiety Disorder",
  "Substance/Medication-Induced Anxiety Disorder",
  "Anxiety Disorder Due to Another Medical Condition",
  "Other Specified Anxiety Disorder",
  "Unspecified Anxiety Disorder",

  "Obsessive-Compulsive Disorder",
  "Body Dysmorphic Disorder",
  "Hoarding Disorder",
  "Trichotillomania (Hair-Pulling Disorder)",
  "Excoriation (Skin-Picking) Disorder",
  "Substance/Medication-Induced Obsessive-Compulsive and Related Disorder",
  "Obsessive-Compulsive and Related Disorder Due to Another Medical Condition",
  "Other Specified Obsessive-Compulsive and Related Disorder",
  "Unspecified Obsessive-Compulsive and Related Disorder",

  "Reactive Attachment Disorder",
  "Disinhibited Social Engagement Disorder",
  "Posttraumatic Stress Disorder",
  "Posttraumatic Stress Disorder in Individuals Older Than 6 Years",
  "Posttraumatic Stress Disorder in Children 6 Years and Younger",
  "Acute Stress Disorder",
  "Adjustment Disorders",
  "Prolonged Grief Disorder",
  "Other Specified Trauma- and Stressor-Related Disorder",
  "Unspecified Trauma- and Stressor-Related Disorder",

  "Dissociative Identity Disorder",
  "Dissociative Amnesia",
  "Depersonalization/Derealization Disorder",
  "Other Specified Dissociative Disorder",
  "Unspecified Dissociative Disorder",

  "Somatic Symptom Disorder",
  "Illness Anxiety Disorder",
  "Functional Neurological Symptom Disorder (Conversion Disorder)",
  "Psychological Factors Affecting Other Medical Conditions",
  "Factitious Disorder",
  "Factitious Disorder Imposed on Self",
  "Factitious Disorder Imposed on Another",
  "Other Specified Somatic Symptom and Related Disorder",
  "Unspecified Somatic Symptom and Related Disorder",

  "Pica",
  "Rumination Disorder",
  "Avoidant/Restrictive Food Intake Disorder",
  "Anorexia Nervosa",
  "Bulimia Nervosa",
  "Binge-Eating Disorder",
  "Other Specified Feeding or Eating Disorder",
  "Unspecified Feeding or Eating Disorder",

  "Enuresis",
  "Encopresis",
  "Other Specified Elimination Disorder",
  "Unspecified Elimination Disorder",

  "Insomnia Disorder",
  "Hypersomnolence Disorder",
  "Narcolepsy",
  "Obstructive Sleep Apnea Hypopnea",
  "Central Sleep Apnea",
  "Sleep-Related Hypoventilation",
  "Circadian Rhythm Sleep-Wake Disorder",
  "Non–Rapid Eye Movement Sleep Arousal Disorders",
  "Nightmare Disorder",
  "Rapid Eye Movement Sleep Behavior Disorder",
  "Restless Legs Syndrome",
  "Substance/Medication-Induced Sleep Disorder",
  "Other Specified Insomnia Disorder",
  "Unspecified Insomnia Disorder",
  "Other Specified Hypersomnolence Disorder",
  "Unspecified Hypersomnolence Disorder",
  "Other Specified Sleep-Wake Disorder",
  "Unspecified Sleep-Wake Disorder",

  "Delayed Ejaculation",
  "Erectile Disorder",
  "Female Orgasmic Disorder",
  "Female Sexual Interest/Arousal Disorder",
  "Genito-Pelvic Pain/Penetration Disorder",
  "Male Hypoactive Sexual Desire Disorder",
  "Premature (Early) Ejaculation",
  "Substance/Medication-Induced Sexual Dysfunction",
  "Other Specified Sexual Dysfunction",
  "Unspecified Sexual Dysfunction",

  "Gender Dysphoria in Children",
  "Gender Dysphoria in Adolescents and Adults",
  "Other Specified Gender Dysphoria",
  "Unspecified Gender Dysphoria",

  "Oppositional Defiant Disorder",
  "Intermittent Explosive Disorder",
  "Conduct Disorder",
  "Antisocial Personality Disorder",
  "Pyromania",
  "Kleptomania",
  "Other Specified Disruptive, Impulse-Control, and Conduct Disorder",
  "Unspecified Disruptive, Impulse-Control, and Conduct Disorder",

  "Alcohol Use Disorder",
  "Alcohol Intoxication",
  "Alcohol Withdrawal",
  "Alcohol-Induced Psychotic Disorder",
  "Alcohol-Induced Bipolar and Related Disorder",
  "Alcohol-Induced Depressive Disorder",
  "Alcohol-Induced Anxiety Disorder",
  "Alcohol-Induced Sleep Disorder",
  "Alcohol-Induced Sexual Dysfunction",
  "Alcohol Intoxication Delirium",
  "Alcohol Withdrawal Delirium",
  "Alcohol-Induced Major Neurocognitive Disorder",
  "Alcohol-Induced Mild Neurocognitive Disorder",
  "Unspecified Alcohol-Related Disorder",

  "Caffeine Intoxication",
  "Caffeine Withdrawal",
  "Caffeine-Induced Anxiety Disorder",
  "Caffeine-Induced Sleep Disorder",
  "Unspecified Caffeine-Related Disorder",

  "Cannabis Use Disorder",
  "Cannabis Intoxication",
  "Cannabis Withdrawal",
  "Cannabis-Induced Psychotic Disorder",
  "Cannabis-Induced Anxiety Disorder",
  "Cannabis-Induced Sleep Disorder",
  "Cannabis Intoxication Delirium",
  "Unspecified Cannabis-Related Disorder",

  "Phencyclidine Use Disorder",
  "Other Hallucinogen Use Disorder",
  "Phencyclidine Intoxication",
  "Other Hallucinogen Intoxication",
  "Hallucinogen Persisting Perception Disorder",
  "Phencyclidine-Induced Psychotic Disorder",
  "Phencyclidine-Induced Bipolar and Related Disorder",
  "Phencyclidine-Induced Depressive Disorder",
  "Phencyclidine-Induced Anxiety Disorder",
  "Phencyclidine Intoxication Delirium",
  "Other Hallucinogen–Induced Psychotic Disorder",
  "Other Hallucinogen–Induced Bipolar and Related Disorder",
  "Other Hallucinogen–Induced Depressive Disorder",
  "Other Hallucinogen-Induced Anxiety Disorder",
  "Other Hallucinogen Intoxication Delirium",
  "Unspecified Phencyclidine-Related Disorder",
  "Unspecified Hallucinogen-Related Disorder",

  "Inhalant Use Disorder",
  "Inhalant Intoxication",
  "Inhalant-Induced Psychotic Disorder",
  "Inhalant-Induced Depressive Disorder",
  "Inhalant-Induced Anxiety Disorder",
  "Inhalant Intoxication Delirium",
  "Inhalant-Induced Major Neurocognitive Disorder",
  "Inhalant-Induced Mild Neurocognitive Disorder",
  "Unspecified Inhalant-Related Disorder",

  "Opioid Use Disorder",
  "Opioid Intoxication",
  "Opioid Withdrawal",
  "Opioid-Induced Depressive Disorder",
  "Opioid-Induced Anxiety Disorder",
  "Opioid-Induced Sleep Disorder",
  "Opioid-Induced Sexual Dysfunction",
  "Opioid Intoxication Delirium",
  "Opioid Withdrawal Delirium",
  "Opioid-Induced Delirium",
  "Unspecified Opioid-Related Disorder",

  "Sedative, Hypnotic, or Anxiolytic Use Disorder",
  "Sedative, Hypnotic, or Anxiolytic Intoxication",
  "Sedative, Hypnotic, or Anxiolytic Withdrawal",
  "Sedative, Hypnotic, or Anxiolytic-Induced Psychotic Disorder",
  "Sedative, Hypnotic, or Anxiolytic-Induced Bipolar and Related Disorder",
  "Sedative, Hypnotic, or Anxiolytic-Induced Depressive Disorder",
  "Sedative, Hypnotic, or Anxiolytic-Induced Anxiety Disorder",
  "Sedative, Hypnotic, or Anxiolytic-Induced Sleep Disorder",
  "Sedative, Hypnotic, or Anxiolytic-Induced Sexual Dysfunction",
  "Sedative, Hypnotic, or Anxiolytic Intoxication Delirium",
  "Sedative, Hypnotic, or Anxiolytic Withdrawal Delirium",
  "Sedative, Hypnotic, or Anxiolytic-Induced Delirium",
  "Sedative, Hypnotic, or Anxiolytic-Induced Major Neurocognitive Disorder",
  "Sedative, Hypnotic, or Anxiolytic-Induced Mild Neurocognitive Disorder",
  "Unspecified Sedative, Hypnotic, or Anxiolytic-Related Disorder",

  "Stimulant Use Disorder",
  "Stimulant Intoxication",
  "Stimulant Withdrawal",
  "Amphetamine-Type Substance (or Other Stimulant)–Induced Psychotic Disorder",
  "Cocaine-Induced Psychotic Disorder",
  "Amphetamine-Type Substance (or Other Stimulant)–Induced Bipolar and Related Disorder",
  "Cocaine-Induced Bipolar and Related Disorder",
  "Amphetamine-Type Substance (or Other Stimulant)–Induced Depressive Disorder",
  "Cocaine-Induced Depressive Disorder",
  "Amphetamine-Type Substance (or Other Stimulant)–Induced Anxiety Disorder",
  "Cocaine-Induced Anxiety Disorder",
  "Amphetamine-Type Substance (or Other Stimulant)–Induced Obsessive-Compulsive and Related Disorder",
  "Cocaine-Induced Obsessive-Compulsive and Related Disorder",
  "Amphetamine-Type Substance (or Other Stimulant)–Induced Sleep Disorder",
  "Cocaine-Induced Sleep Disorder",
  "Amphetamine-Type Substance (or Other Stimulant)–Induced Sexual Dysfunction",
  "Cocaine-Induced Sexual Dysfunction",
  "Amphetamine-Type Substance (or Other Stimulant) Intoxication Delirium",
  "Cocaine Intoxication Delirium",
  "Amphetamine-Type Substance (or Other Stimulant)–Induced Mild Neurocognitive Disorder",
  "Cocaine-Induced Mild Neurocognitive Disorder",
  "Unspecified Stimulant-Related Disorder",

  "Tobacco Use Disorder",
  "Tobacco Withdrawal",
  "Tobacco-Induced Sleep Disorder",
  "Unspecified Tobacco-Related Disorder",

  "Other (or Unknown) Substance Use Disorder",
  "Other (or Unknown) Substance Intoxication",
  "Other (or Unknown) Substance Withdrawal",
  "Other (or Unknown) Substance–Induced Psychotic Disorder",
  "Other (or Unknown) Substance–Induced Bipolar and Related Disorder",
  "Other (or Unknown) Substance–Induced Depressive Disorder",
  "Other (or Unknown) Substance–Induced Anxiety Disorder",
  "Other (or Unknown) Substance–Induced Obsessive-Compulsive and Related Disorder",
  "Other (or Unknown) Substance–Induced Sleep Disorder",
  "Other (or Unknown) Substance–Induced Sexual Dysfunction",
  "Other (or Unknown) Substance Intoxication Delirium",
  "Other (or Unknown) Substance Withdrawal Delirium",
  "Other (or Unknown) Medication–Induced Delirium",
  "Other (or Unknown) Substance–Induced Major Neurocognitive Disorder",
  "Other (or Unknown) Substance–Induced Mild Neurocognitive Disorder",
  "Unspecified Other (or Unknown) Substance–Related Disorder",

  "Gambling Disorder",

  "Delirium",
  "Other Specified Delirium",
  "Unspecified Delirium",

  "Major Neurocognitive Disorder Due to Alzheimer’s Disease",
  "Mild Neurocognitive Disorder Due to Alzheimer’s Disease",
  "Major Neurocognitive Disorder Due to Frontotemporal Degeneration",
  "Mild Neurocognitive Disorder Due to Frontotemporal Degeneration",
  "Major Neurocognitive Disorder With Lewy Bodies",
  "Mild Neurocognitive Disorder With Lewy Bodies",
  "Major Neurocognitive Disorder Due to Vascular Disease",
  "Mild Neurocognitive Disorder Due to Vascular Disease",
  "Major Neurocognitive Disorder Due to Traumatic Brain Injury",
  "Mild Neurocognitive Disorder Due to Traumatic Brain Injury",
  "Substance/Medication-Induced Major Neurocognitive Disorder",
  "Substance/Medication-Induced Mild Neurocognitive Disorder",
  "Major Neurocognitive Disorder Due to HIV Infection",
  "Mild Neurocognitive Disorder Due to HIV Infection",
  "Major Neurocognitive Disorder Due to Prion Disease",
  "Mild Neurocognitive Disorder Due to Prion Disease",
  "Major Neurocognitive Disorder Due to Parkinson’s Disease",
  "Mild Neurocognitive Disorder Due to Parkinson’s Disease",
  "Major Neurocognitive Disorder Due to Huntington’s Disease",
  "Mild Neurocognitive Disorder Due to Huntington’s Disease",
  "Major Neurocognitive Disorder Due to Another Medical Condition",
  "Mild Neurocognitive Disorder Due to Another Medical Condition",
  "Major Neurocognitive Disorder Due to Multiple Etiologies",
  "Mild Neurocognitive Disorder Due to Multiple Etiologies",
  "Unspecified Neurocognitive Disorder",

  "Paranoid Personality Disorder",
  "Schizoid Personality Disorder",
  "Schizotypal Personality Disorder",
  "Borderline Personality Disorder",
  "Histrionic Personality Disorder",
  "Narcissistic Personality Disorder",
  "Avoidant Personality Disorder",
  "Dependent Personality Disorder",
  "Obsessive-Compulsive Personality Disorder",
  "Personality Change Due to Another Medical Condition",
  "Other Specified Personality Disorder",
  "Unspecified Personality Disorder",

  "Voyeuristic Disorder",
  "Exhibitionistic Disorder",
  "Frotteuristic Disorder",
  "Sexual Masochism Disorder",
  "Sexual Sadism Disorder",
  "Pedophilic Disorder",
  "Fetishistic Disorder",
  "Transvestic Disorder",
  "Other Specified Paraphilic Disorder",
  "Unspecified Paraphilic Disorder",

  "Other Specified Mental Disorder Due to Another Medical Condition",
  "Unspecified Mental Disorder Due to Another Medical Condition",
  "Other Specified Mental Disorder",
  "Unspecified Mental Disorder"
]